providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones

  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN

zones:
  richit.me.:
    sources:
      - config
    targets:
      - cloudflare
    safe_mode: false

  richitb.com.:
    sources:
      - config
    targets:
      - cloudflare

  debugcrew.tech.:
    sources:
      - config
    targets:
      - cloudflare